export const sample_data = {
  id: "root",
  type: "layout",
  columns: "1",
  rows: "1",
  colspan: "1",
  rowspan: "1",
  childs: [
    {
      id: "item1",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item2",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item3",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item4",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item5",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item6",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item7",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item8",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item9",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item10",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item11",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item12",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item13",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item14",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
    {
      id: "item15",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      childs: [],
    },
  ],
};
