export const sample_data = {
  id: "root",
  type: "layout",
  columns: "2",
  rows: "2",
  childs: [
    {
      id: "layout1",
      type: "layout",
      columns: "2",
      rows: "2",
      childs: [
        {
          id: "item1",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
        {
          id: "item2",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
        {
          id: "itemExtra1",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
        {
          id: "itemExtra2",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
        {
          id: "itemExtra6",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
        {
          id: "itemExtra7",
          type: "content",
          columns: "2",
          rows: "2",
          childs: [],
        },
      ],
    },
    {
      id: "item3",
      type: "content",
      columns: "2",
      rows: "2",
      childs: [],
    },
    {
      id: "layout2",
      type: "layout",
      columns: "2",
      rows: "2",
      childs: [
        {
          id: "item4",
          type: "layout",
          columns: "2",
          rows: "2",
          childs: [
            {
              id: "item5",
              type: "content",
              columns: "2",
              rows: "2",
              childs: [],
            },
            {
              id: "item6",
              type: "content",
              columns: "2",
              rows: "2",
              childs: [],
            },
            {
              id: "itemExtra3",
              type: "content",
              columns: "2",
              rows: "2",
              childs: [],
            },
            {
              id: "itemExtra8",
              type: "content",
              columns: "2",
              rows: "2",
              childs: [],
            },
            {
              id: "itemExtra9",
              type: "content",
              columns: "2",
              rows: "2",
              childs: [],
            },
          ],
        },
        {
          id: "layoutExtra1",
          type: "layout",
          columns: "3",
          rows: "3",
          childs: [
            {
              id: "itemExtra4",
              type: "content",
              columns: "3",
              rows: "3",
              childs: [],
            },
            {
              id: "itemExtra5",
              type: "content",
              columns: "3",
              rows: "3",
              childs: [],
            },
            {
              id: "itemExtra10",
              type: "content",
              columns: "3",
              rows: "3",
              childs: [],
            },
          ],
        },
        {
          id: "layoutExtra2",
          type: "layout",
          columns: "4",
          rows: "4",
          childs: [
            {
              id: "itemExtra11",
              type: "content",
              columns: "4",
              rows: "4",
              childs: [],
            },
            {
              id: "itemExtra12",
              type: "content",
              columns: "4",
              rows: "4",
              childs: [],
            },
            {
              id: "itemExtra13",
              type: "content",
              columns: "4",
              rows: "4",
              childs: [],
            },
          ],
        },
      ],
    },
    {
      id: "layout3",
      type: "layout",
      columns: "3",
      rows: "3",
      childs: [
        {
          id: "itemExtra14",
          type: "content",
          columns: "3",
          rows: "3",
          childs: [],
        },
        {
          id: "itemExtra15",
          type: "content",
          columns: "3",
          rows: "3",
          childs: [],
        },
      ],
    },
  ],
};
