import {Editor, HomePage} from "../pages";

export const colors = {
  c1: "#4c8aff",
  c2: "#52F988",
};

export const Enum = {
  srkey: "fkzeVxJ3Y8baiqTWkGj3GrQOdk59dc",
};

export const sample_data = {
  id: "root",
  type: "grid",
  columns: "1",
  rows: "1",
  colspan: "1",
  rowspan: "1",
  gap: "1",
  alignItems: "flex-start",
  justifyContent: "flex-start",
  style: {},
  childs: [
    {
      id: "item1",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item2",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item3",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item4",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item5",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item6",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item7",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item8",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item9",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item10",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item11",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item12",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item13",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item14",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
    {
      id: "item15",
      type: "content",
      columns: "1",
      rows: "1",
      colspan: "1",
      rowspan: "1",
      gap: "1",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      style: {},
      childs: [],
    },
  ],
};
